# Generated by Django 4.0.3 on 2022-03-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=50)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(max_length=250)),
                ('nr_domu', models.CharField(max_length=5)),
                ('nr_mieszkania', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=11)),
                ('is_staff', models.BooleanField(default=False)),
                ('specjalizacja', models.CharField(max_length=100)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepta.adres')),
            ],
        ),
        migrations.CreateModel(
            name='recepta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wystawienia', models.DateTimeField(auto_now_add=True)),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacjent', to='recepta.osoba')),
                ('wystawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepta.osoba')),
            ],
        ),
        migrations.CreateModel(
            name='przepisane_leki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_leku', models.CharField(max_length=250)),
                ('dawkowanie', models.CharField(max_length=2000)),
                ('odplatnosc', models.IntegerField()),
                ('recepta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepta.recepta')),
            ],
        ),
    ]
