# Generated by Django 4.0.3 on 2022-03-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adres',
            options={'ordering': ('miasto',), 'verbose_name': 'Adres', 'verbose_name_plural': 'Adresy'},
        ),
    ]
