# Generated by Django 4.0.3 on 2022-03-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepta', '0002_alter_adres_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ('nazwisko',), 'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterModelOptions(
            name='przepisane_leki',
            options={'ordering': ('nazwa_leku',), 'verbose_name': 'Lek', 'verbose_name_plural': 'Leki'},
        ),
        migrations.AlterModelOptions(
            name='recepta',
            options={'ordering': ('-data_wystawienia',), 'verbose_name': 'Recepta', 'verbose_name_plural': 'Recepty'},
        ),
    ]
