# Generated by Django 4.0.3 on 2022-03-27 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=40)),
                ('kodPocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(max_length=150)),
                ('nr_dom', models.CharField(max_length=10)),
                ('nr_mieszkania', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPacjent', models.IntegerField()),
                ('imie', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=60)),
                ('pesel', models.CharField(max_length=11)),
                ('is_staff', models.BooleanField(default=False)),
                ('specjalizacja', models.CharField(default=1, max_length=100)),
                ('adres', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projekt.adres')),
            ],
        ),
        migrations.CreateModel(
            name='Recepta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataWystawienia', models.DateTimeField(auto_now_add=True)),
                ('idPacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacjent', to='projekt.osoba')),
                ('wystawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.osoba')),
            ],
        ),
    ]
