# Generated by Django 4.0.3 on 2022-03-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name': 'Adres', 'verbose_name_plural': 'Adresy'},
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterModelOptions(
            name='recepta',
            options={'verbose_name': 'Recepta', 'verbose_name_plural': 'Recepty'},
        ),
        migrations.CreateModel(
            name='Przepisane_leki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_leku', models.CharField(max_length=250)),
                ('dawkowanie', models.CharField(max_length=2000)),
                ('odplatnosc', models.IntegerField()),
                ('recepta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.recepta')),
            ],
            options={
                'verbose_name': 'Przepisane Leki',
                'verbose_name_plural': 'Przepisane Leki',
            },
        ),
    ]
